<form class="" action="<?php echo $block->getBaseUrl().'job/index/save'; ?>" id="test-job-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <br/>
        <div class="field title">
            <label class="label" for="title"><span>Name</span></label>
            <div class="control">
                <input name="fullname" id="title" title="Name" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field email">
            <label class="label" for="email"><span>Email</span></label>
            <div class="control">
                <input name="email" id="email" title="Email" value="" class="input-text" type="text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field contactno">
            <label class="label" for="contactno"><span>Contact Number</span></label>
            <div class="control">
                <input name="contactno" maxlength="10" id="contactno" title="Contact Number" value="" class="input-text" type="text" data-validate="{required:true, 'validate-number':true}">
            </div>
        </div>
        <div class="field resume">
            <label class="label" for="resume"><span>Resume</span></label>
            <div class="control">
                <input name="resume" id="resume" title="Resume" value="" class="input-text" type="file" data-validate="{required:true}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>